//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSIGN
    {
        public string RECEIVER { get; set; }
        public string REC_LINE { get; set; }
        public string CCN { get; set; }
        public string Priority { get; set; }
        public string Assign1 { get; set; }
        public string Notes { get; set; }
    }
}
