//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTCH_TEMP
    {
        public string RECEIVER { get; set; }
        public string REC_LINE { get; set; }
        public string FILE_NAME { get; set; }
        public byte[] ATT_FILE { get; set; }
        public string USER_ { get; set; }
        public System.DateTime USER_DATE { get; set; }
        public string PC_NAME { get; set; }
    }
}
