//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute
    {
        public int ID_auto1 { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<System.DateTime> Partial_date { get; set; }
        public Nullable<double> Partial_Acc { get; set; }
        public Nullable<double> Partial_Rej { get; set; }
        public string Inspector { get; set; }
        public string Remark { get; set; }
        public Nullable<double> A { get; set; }
        public string AA { get; set; }
        public Nullable<double> B { get; set; }
        public string BB { get; set; }
        public Nullable<double> C { get; set; }
        public string CC { get; set; }
        public Nullable<double> D { get; set; }
        public string DD { get; set; }
        public Nullable<double> E { get; set; }
        public string EE { get; set; }
        public Nullable<double> F { get; set; }
        public string FF { get; set; }
        public string De1 { get; set; }
        public string De2 { get; set; }
        public string De3 { get; set; }
        public string De4 { get; set; }
        public string De5 { get; set; }
        public string De6 { get; set; }
        public string Re1 { get; set; }
        public string Re2 { get; set; }
        public string Re3 { get; set; }
        public string Re4 { get; set; }
        public string Re5 { get; set; }
        public string Re6 { get; set; }
        public string Di1 { get; set; }
        public string Di2 { get; set; }
        public string Di3 { get; set; }
        public string Di4 { get; set; }
        public string Di5 { get; set; }
        public string Di6 { get; set; }
    }
}
