//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHANGED_SPL
    {
        public string RECEIVER { get; set; }
        public string REC_LINE { get; set; }
        public double SAMPLING_MEASURE { get; set; }
        public double SAMPLING_VISUAL { get; set; }
        public string SEC { get; set; }
        public string USER_ { get; set; }
        public System.DateTime USER_DATE { get; set; }
        public string REASON { get; set; }
        public string AQL_VISUAL { get; set; }
        public string AQL_MEASURE { get; set; }
        public string CCN { get; set; }
    }
}
