//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_HIS
    {
        public string ITEM { get; set; }
        public string ITEM_DESC { get; set; }
        public string STOCK_UM { get; set; }
        public string VENDOR { get; set; }
        public string VEN_NAME { get; set; }
        public string PO_NUM { get; set; }
        public string PO_LINE { get; set; }
        public string QS_STAT { get; set; }
        public string RECEIVER { get; set; }
        public string REC_LINE { get; set; }
        public string LOT { get; set; }
        public string HALT { get; set; }
        public double QTY { get; set; }
        public System.DateTime POSTING_DATE { get; set; }
        public string USER_ { get; set; }
        public System.DateTime USER_DATE { get; set; }
        public string PC_NAME { get; set; }
        public double SAMPLING_VISUAL { get; set; }
        public double SAMPLING_MEASURE { get; set; }
        public string SEC { get; set; }
        public string SERIAL_CTL { get; set; }
        public string SKIP_LOT_PLAN { get; set; }
        public string SKIP_LOT_LEVEL { get; set; }
        public string INSP_STAT { get; set; }
        public string DOC_REQ { get; set; }
        public string STATUS { get; set; }
        public string QUAL { get; set; }
        public string SKIP_LEVEL { get; set; }
        public Nullable<int> LOT_SKIP { get; set; }
        public string AQL_VISUAL { get; set; }
        public string AQL_MEASURE { get; set; }
        public string TEST_ROSH_REQUIRED { get; set; }
        public string CCN { get; set; }
    }
}
