//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESCAPING_PPM
    {
        public string NCR_NUM { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string ANALYST { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<System.DateTime> PERIOD { get; set; }
        public Nullable<System.DateTime> DATEIMPORT { get; set; }
        public string USERIMPORT { get; set; }
        public int ID { get; set; }
    }
}
