//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRSTLOT
    {
        public string ITEM { get; set; }
        public string DESCR { get; set; }
        public string VENDOR { get; set; }
        public string VEN_NAME { get; set; }
        public string RECEIVER { get; set; }
        public System.DateTime REC_DATE { get; set; }
        public string CCN { get; set; }
    }
}
