//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIXTURE_ACT_BY_SPL_NoUse
    {
        public string RECEIVER { get; set; }
        public string REC_LINE { get; set; }
        public string SEC { get; set; }
        public string ITEM { get; set; }
        public string DRAW_REV { get; set; }
        public string SPL_NUM { get; set; }
        public string SERIAL_NUM { get; set; }
        public string FIXTURE { get; set; }
        public string CRITIAL { get; set; }
        public string EVALUATION { get; set; }
    }
}
