//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIXTURE_STD_BY_PART_OLD_NoUse
    {
        public string ITEM { get; set; }
        public string DRAW_REV { get; set; }
        public string FIXTURE { get; set; }
        public string FIXTURE_DESC { get; set; }
        public string CRITIAL { get; set; }
        public string EVA_METHOD { get; set; }
    }
}
