//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAST_SKIP_LOT_LEVEL_bk
    {
        public string ITEM { get; set; }
        public string VENDOR { get; set; }
        public string VEN_NAME { get; set; }
        public string LAST_LOT_SKIP { get; set; }
        public string JUDGEMENT { get; set; }
        public System.DateTime JUDGE_DATE { get; set; }
        public string LEVEL { get; set; }
        public int LAST_LOT { get; set; }
        public string INS_STAT { get; set; }
        public string LAST_REC { get; set; }
        public string LAST_REC_LINE { get; set; }
        public string CCN { get; set; }
    }
}
