//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        public string USER_NAME { get; set; }
        public string PASS { get; set; }
        public string PERMIT { get; set; }
        public string ROLE { get; set; }
        public string FNAME { get; set; }
        public string USER_NET { get; set; }
        public string ENABLE { get; set; }
    }
}
