//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAILHISTORY
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public string AttachFile { get; set; }
        public string To { get; set; }
        public string CC { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Creater { get; set; }
        public string Type { get; set; }
    }
}
