//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAINQUESTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAINQUESTION()
        {
            this.DETAILQUESTIONs = new HashSet<DETAILQUESTION>();
            this.DETAILQUESTIONs1 = new HashSet<DETAILQUESTION>();
        }
    
        public int ID { get; set; }
        public string CONTENT { get; set; }
        public Nullable<System.DateTime> WRITEDATE { get; set; }
        public string WRITEBY { get; set; }
        public Nullable<bool> PUBLICQUESTION { get; set; }
        public Nullable<System.DateTime> PUBLICDATE { get; set; }
        public string PUBLICBY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAILQUESTION> DETAILQUESTIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAILQUESTION> DETAILQUESTIONs1 { get; set; }
    }
}
