//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEASUREMENT_STD_BY_PART
    {
        public string CCN { get; set; }
        public string ITEM { get; set; }
        public string DRAW_REV { get; set; }
        public string REV { get; set; }
        public string MEASURE_PARA { get; set; }
        public string MEASURE_PARA_DESC { get; set; }
        public string EVA_METHOD { get; set; }
        public string TOOL_FIXTURE { get; set; }
        public Nullable<double> LVALUE { get; set; }
        public Nullable<double> UVALUE { get; set; }
        public string UNIT { get; set; }
        public string CRITIAL { get; set; }
        public string USER_ { get; set; }
        public System.DateTime USER_DATE { get; set; }
        public string PC_NAME { get; set; }
        public string MeasureSize { get; set; }
    }
}
