//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEETING_ATT
    {
        public string MINUTES_NUM { get; set; }
        public string ATT_PATH { get; set; }
        public string FILE_NAME { get; set; }
    }
}
