//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEETING_NOTE
    {
        public string MINUTES_NUM { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string SUBJECT { get; set; }
        public string MINUTES_CONTENT { get; set; }
        public System.DateTime MEETING_DATE { get; set; }
        public string STATUS { get; set; }
    }
}
