//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NC_BY_PRODUCT_GRP
    {
        public string CCN { get; set; }
        public string PRODUCT_GRP { get; set; }
        public string DEF_CODE { get; set; }
    }
}
