//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCR_EVI
    {
        public string NCR_NUM { get; set; }
        public string SEC { get; set; }
        public string EVI_PATH { get; set; }
        public int EVI_ID { get; set; }
        public Nullable<bool> IsPrint { get; set; }
    }
}
