//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PANEL_EXCEL
    {
        public string VENDOR { get; set; }
        public double EARLY { get; set; }
        public double LATE { get; set; }
        public double ONTIME { get; set; }
        public double TOTAL { get; set; }
        public double TARGET { get; set; }
        public double ACTUAL { get; set; }
        public System.DateTime Month { get; set; }
    }
}
