//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PART_INS_REQ
    {
        public string CCN { get; set; }
        public string ITEM { get; set; }
        public string DRAW_REV { get; set; }
        public string REV { get; set; }
        public string POL_GRP { get; set; }
        public string AQL_VISUAL { get; set; }
        public string AQL_MEASURE { get; set; }
        public string SERIAL_CTL { get; set; }
        public string SKIP_LOT_CTL { get; set; }
        public string DOC_REQUIRED { get; set; }
        public string TEST_ROSH_REQUIRED { get; set; }
        public string USER_ { get; set; }
        public Nullable<System.DateTime> USER_DATE { get; set; }
        public string PC_NAME { get; set; }
        public string DRAWING_PATH { get; set; }
        public string USER_APPROVE { get; set; }
        public string APPROVED { get; set; }
        public Nullable<System.DateTime> APPROVED_DATE { get; set; }
        public string PRODUCT_GRP { get; set; }
    }
}
