//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PART_INS_REQ_APPROVE
    {
        public string CCN { get; set; }
        public string ITEM { get; set; }
        public string DRAW_REV { get; set; }
        public string REV { get; set; }
        public string USER_APPROVE { get; set; }
        public string APPROVED { get; set; }
        public Nullable<System.DateTime> APPROVED_DATE { get; set; }
    }
}
