//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PART_REJECT
    {
        public string CCN { get; set; }
        public string ITEM { get; set; }
        public string DRAW_REV { get; set; }
        public string REV { get; set; }
        public string USER_REJECT { get; set; }
        public string COMMENT { get; set; }
        public System.DateTime DATE { get; set; }
    }
}
