//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PART_INS_REQ_OLD
    {
        public string ITEM { get; set; }
        public string DRAW_REV { get; set; }
        public string AQL_VISUAL { get; set; }
        public string AQL_MEASURE { get; set; }
        public string SERIAL_CTL { get; set; }
        public string SKIP_LOT_CTL { get; set; }
        public string DOC_REQUIRED { get; set; }
    }
}
