//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PART_INFO_TEMP
    {
        public string CCN { get; set; }
        public string ITEM { get; set; }
        public string DESCR { get; set; }
        public string DRAW_REV { get; set; }
        public string REC_RULE { get; set; }
        public System.DateTime INPUT { get; set; }
        public string EMPLOYEE { get; set; }
        public string ANALYST { get; set; }
        public string PRODUCT_GRP { get; set; }
    }
}
