//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO
    {
        public int ID { get; set; }
        public string PO1 { get; set; }
        public string PN { get; set; }
        public string Description { get; set; }
        public string Supplier_code { get; set; }
        public string Supplier { get; set; }
        public string Rev { get; set; }
        public string Status { get; set; }
        public Nullable<double> Qty { get; set; }
        public string Unit { get; set; }
        public string CoC { get; set; }
        public string Required_inspection { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Remark { get; set; }
        public string Report { get; set; }
        public string AQLM { get; set; }
        public string AQLV { get; set; }
        public string SPL1 { get; set; }
        public string SPL2 { get; set; }
        public string Result1 { get; set; }
        public string Result2 { get; set; }
        public string Action { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Wide { get; set; }
        public Nullable<double> Thickness { get; set; }
        public Nullable<double> Tab_gap { get; set; }
        public Nullable<double> Edge_gap { get; set; }
        public string Judgement { get; set; }
        public string NCR { get; set; }
        public Nullable<System.DateTime> Feedback_date { get; set; }
        public string Feedback_to { get; set; }
        public string SCAR { get; set; }
        public string RMA { get; set; }
        public Nullable<double> Return_Qty { get; set; }
        public Nullable<double> Credit_Qty { get; set; }
        public string Return_notes { get; set; }
        public string IQA_Status { get; set; }
        public Nullable<System.DateTime> Closed_Date { get; set; }
        public string CA { get; set; }
        public Nullable<int> Gen_Remark { get; set; }
        public Nullable<System.DateTime> NCR_writen_Date { get; set; }
        public Nullable<System.DateTime> Last_signed_Date { get; set; }
        public string Note { get; set; }
    }
}
