//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCAREMAIL
    {
        public int ID { get; set; }
        public int SCAR_ID { get; set; }
        public string SUBJECT { get; set; }
        public string CONTENT { get; set; }
        public string FILENAME { get; set; }
        public string SENTTO { get; set; }
        public string CC { get; set; }
        public string SCARID { get; set; }
        public string NCRFILE { get; set; }
    
        public virtual SCARINFO SCARINFO { get; set; }
    }
}
