//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCARINFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCARINFO()
        {
            this.SCAREMAILs = new HashSet<SCAREMAIL>();
        }
    
        public int ID { get; set; }
        public string VENDOR { get; set; }
        public string PUR_LOC { get; set; }
        public int NON_QTY { get; set; }
        public string RMA { get; set; }
        public string NCR_NUMBER { get; set; }
        public string PO_NUMBER { get; set; }
        public string ITEM { get; set; }
        public string BUYER { get; set; }
        public string QUALITY { get; set; }
        public string VN_SCAR { get; set; }
        public string VN_NCR { get; set; }
        public string PROBLEM { get; set; }
        public System.DateTime DATEPROBLEM { get; set; }
        public System.DateTime DATERESPOND { get; set; }
        public string WRITTENBY { get; set; }
        public System.DateTime WRITTENDATE { get; set; }
        public string STATUS { get; set; }
        public int VERSION { get; set; }
        public string SCAR_ID { get; set; }
        public string MI_PART_NO { get; set; }
        public string LOT { get; set; }
        public string CONTENT { get; set; }
        public string SUPPLIER_REPRESENTATIVE { get; set; }
        public Nullable<System.DateTime> DATE_D8 { get; set; }
        public string ACKNOWLEDGEMENT { get; set; }
        public string SCAR_STATUS { get; set; }
        public string EDIVENCE_D8 { get; set; }
        public string DEFECTCODE { get; set; }
        public string RECURING_PROBLEM { get; set; }
        public string CATEGORY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCAREMAIL> SCAREMAILs { get; set; }
    }
}
