//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCAR_INFO_BACKUP
    {
        public int ID { get; set; }
        public int SCAR_ID { get; set; }
        public string VENDOR { get; set; }
        public int NON_QTY { get; set; }
        public string RMA { get; set; }
        public string NCR_NUMBER { get; set; }
        public string PO_NUMBER { get; set; }
        public string ITEM { get; set; }
        public string BUYER { get; set; }
        public string QUALITY { get; set; }
        public string VN_SCAR { get; set; }
        public string VN_NCR { get; set; }
        public string PROBLEM { get; set; }
        public System.DateTime DATEPROBLEM { get; set; }
        public System.DateTime DATERESPOND { get; set; }
        public string WRITTENBY { get; set; }
        public System.DateTime WRITTENDATE { get; set; }
        public string STATUS { get; set; }
        public int VERSION { get; set; }
        public string MI_PART_NO { get; set; }
        public string LOT { get; set; }
        public string REASON { get; set; }
        public string WRITERREJECT { get; set; }
        public System.DateTime DATEREJECT { get; set; }
        public string RECURING_PROBLEM { get; set; }
    }
}
