//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKIP_LOT_LEVEL_bk
    {
        public string LEVEL { get; set; }
        public string NEXT_LEV1 { get; set; }
        public string NEXT_LEV2 { get; set; }
        public int RATE { get; set; }
        public Nullable<int> MAX_LOT { get; set; }
    }
}
