//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    
    public partial class sp_GetNCRAging_Result1
    {
        public string NCR_NUM { get; set; }
        public Nullable<double> Amount { get; set; }
        public string MI_PART_NO { get; set; }
        public string user_submit { get; set; }
        public string User_Disposition { get; set; }
        public string Approver { get; set; }
        public string PO_NUM { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public Nullable<System.DateTime> DATESUBMIT { get; set; }
        public Nullable<System.DateTime> DateApproval { get; set; }
        public Nullable<int> AGE { get; set; }
        public string status { get; set; }
    }
}
