//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIER_PPM
    {
        public string CCN { get; set; }
        public int FY { get; set; }
        public Nullable<int> TYPE { get; set; }
        public string VENDOR { get; set; }
        public string PUR_LOC { get; set; }
    }
}
