//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskHi
    {
        public int TaskIDHIs { get; set; }
        public string Status { get; set; }
        public string UserCreate { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Level { get; set; }
        public int ID_His { get; set; }
    }
}
