//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASKLIST
    {
        public int TopicID { get; set; }
        public string Topic { get; set; }
        public string TYPE { get; set; }
        public string WRITTENBY { get; set; }
        public Nullable<System.DateTime> WRITEDATE { get; set; }
        public string Task_Detail { get; set; }
        public Nullable<int> Level { get; set; }
        public string Reference { get; set; }
    }
}
