//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK_APPROVE
    {
        public string TASK_ID { get; set; }
        public string APPROVER { get; set; }
        public Nullable<System.DateTime> APPROVED_DATE { get; set; }
        public string FLAG { get; set; }
        public string EMAIL { get; set; }
    }
}
