//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDashboard_Guide_Show
    {
        public string FileName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int Sq { get; set; }
        public string Path { get; set; }
        public string Path_Upload { get; set; }
        public string Title { get; set; }
    }
}
