//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbFixture
    {
        public string ID { get; set; }
        public string Des { get; set; }
        public string Status { get; set; }
        public string Line { get; set; }
        public string YN { get; set; }
        public string Kind { get; set; }
        public string Date { get; set; }
        public string Frequency { get; set; }
        public string EquipType { get; set; }
        public string YN_2 { get; set; }
        public string Frequency_2 { get; set; }
        public string Date_2 { get; set; }
        public string LinkData { get; set; }
    }
}
