//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Inv_Step1_SubmitSuggestion
    {
        public string Sug_ID { get; set; }
        public string Sug_Type { get; set; }
        public string Sug_title { get; set; }
        public string Cur_prob { get; set; }
        public string Idea_impr { get; set; }
        public string Cur_Step { get; set; }
        public Nullable<System.DateTime> Exp_Start_Date { get; set; }
        public Nullable<System.DateTime> Exp_End_date { get; set; }
        public Nullable<System.DateTime> Submit_date { get; set; }
        public string Submitter { get; set; }
        public string Requestor { get; set; }
        public string Rqtor_name { get; set; }
        public string Req_Dept { get; set; }
        public string Req_Email { get; set; }
        public string Att_File_Current { get; set; }
        public string Att_File_Idea { get; set; }
    }
}
