//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Inv_Step2_CIAproval
    {
        public string Sug_ID { get; set; }
        public string Imp_Method { get; set; }
        public string Sponsor { get; set; }
        public string Coacher { get; set; }
        public string Comment { get; set; }
    }
}
