//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RP_Setting_DataGrid
    {
        public long ID { get; set; }
        public long Report_ID { get; set; }
        public byte DataSource_Idx { get; set; }
        public string Col_Name { get; set; }
        public string Col_header { get; set; }
        public Nullable<double> Width { get; set; }
        public string Col_Color { get; set; }
        public string Text_Color { get; set; }
        public string Text_Font { get; set; }
        public Nullable<byte> Text_Size { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
    }
}
