//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RP_Data_Source
    {
        public long ID { get; set; }
        public long Report_ID { get; set; }
        public long Data_Source { get; set; }
        public byte Data_Idx { get; set; }
        public string Data_Title { get; set; }
        public string Title_Color { get; set; }
        public string Title_Font { get; set; }
        public Nullable<double> Title_Size { get; set; }
        public string Show_method { get; set; }
        public string Data_Group { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
    }
}
