//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PT_CheckSheet
    {
        public string Part_Num { get; set; }
        public byte Item_Idx { get; set; }
        public string Item_Desc { get; set; }
        public string Data_Type { get; set; }
        public string Item_Remark { get; set; }
        public Nullable<bool> Is_Require { get; set; }
        public string Item_Value { get; set; }
    }
}
