//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SQE_Ass_Resp_Status
    {
        public long Assessment_ID { get; set; }
        public Nullable<bool> SQE_Status { get; set; }
        public string SQE_User { get; set; }
        public Nullable<System.DateTime> SQE_Date { get; set; }
        public Nullable<bool> Buyer_Status { get; set; }
        public string Buyer_User { get; set; }
        public Nullable<System.DateTime> Buyer_Date { get; set; }
    }
}
