//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Inv_Cost_Saving
    {
        public string Sug_ID { get; set; }
        public Nullable<double> Jan { get; set; }
        public Nullable<double> Feb { get; set; }
        public Nullable<double> Mar { get; set; }
        public Nullable<double> Apr { get; set; }
        public Nullable<double> May { get; set; }
        public Nullable<double> Jun { get; set; }
        public Nullable<double> Jul { get; set; }
        public Nullable<double> Aug { get; set; }
        public Nullable<double> Sep { get; set; }
        public Nullable<double> Oct { get; set; }
        public Nullable<double> Nov { get; set; }
        public Nullable<double> Dec { get; set; }
        public Nullable<double> CostSum { get; set; }
        public string User_Input { get; set; }
        public System.DateTime Date_Input { get; set; }
    }
}
