//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PT_Status
    {
        public string Part_Num { get; set; }
        public byte Step_Idx { get; set; }
        public string Step_Name { get; set; }
        public bool Step_Status { get; set; }
        public Nullable<System.DateTime> Date_Finish { get; set; }
        public string User_Finish { get; set; }
    }
}
