//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Inv_Step4_DirApr
    {
        public string Sug_ID { get; set; }
        public string Director { get; set; }
        public Nullable<bool> App_eva { get; set; }
        public string App_com { get; set; }
        public Nullable<bool> Stra_Link { get; set; }
        public string Stra_com { get; set; }
        public Nullable<bool> Apr_Status { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> Date_Action { get; set; }
    }
}
