//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SOR_Cur_Review_Detail
    {
        public long ITEM_REVIEW_ID { get; set; }
        public string SO_NO { get; set; }
        public System.DateTime DOWNLOAD_DATE { get; set; }
        public string DEPT_REVIEW { get; set; }
        public string ITEM_REVIEW { get; set; }
        public Nullable<bool> RESULT { get; set; }
        public string COMMENT { get; set; }
        public Nullable<System.DateTime> REVIEW_AT { get; set; }
        public string REVIEW_BY { get; set; }
        public Nullable<bool> ISLOCK { get; set; }
        public string LINE { get; set; }
    }
}
