//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SQE_PCN_Attached
    {
        public long ID { get; set; }
        public string PCN_Num { get; set; }
        public string File_Name { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
        public string Uploaded_By { get; set; }
        public Nullable<System.DateTime> Uploaded_At { get; set; }
    }
}
