//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SOR_Family_Setup_Qty
    {
        public int Family_inx { get; set; }
        public string Family { get; set; }
        public double Setup_Qty { get; set; }
        public Nullable<bool> Review_Completed { get; set; }
    }
}
