//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PT_Infor
    {
        public string Part_Num { get; set; }
        public string Description { get; set; }
        public string Plan_Type { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Initial_Note { get; set; }
        public string Build_Loc { get; set; }
        public string Wc { get; set; }
        public Nullable<double> Plan_Yield { get; set; }
        public string Vn_Owner { get; set; }
        public string Setion { get; set; }
        public string PE_Note { get; set; }
        public string PE_User { get; set; }
        public string Initail_User { get; set; }
        public string Status { get; set; }
        public Nullable<double> Yield { get; set; }
        public string GM { get; set; }
        public string FileConclusion { get; set; }
        public string Conclution { get; set; }
    }
}
