//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Inv_Step3_SponsorApr
    {
        public string Sug_ID { get; set; }
        public string Pro_Leader { get; set; }
        public Nullable<System.DateTime> Imp_Start { get; set; }
        public Nullable<System.DateTime> Imp_End { get; set; }
        public Nullable<bool> Tech_abi { get; set; }
        public string Tech_com { get; set; }
        public Nullable<bool> Eco_ben { get; set; }
        public string Eco_com { get; set; }
        public Nullable<bool> Legal_Rel { get; set; }
        public string Legal_com { get; set; }
        public Nullable<bool> Res_avai { get; set; }
        public string Res_com { get; set; }
        public Nullable<bool> Safe_Rel { get; set; }
        public string Safe_com { get; set; }
        public Nullable<bool> Fin_abi { get; set; }
        public string Fin_com { get; set; }
        public string Comment { get; set; }
    }
}
