//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SQE_Customer_Claim
    {
        public long ID { get; set; }
        public string Supplier { get; set; }
        public byte Month { get; set; }
        public int Year { get; set; }
        public string Product { get; set; }
        public string Part { get; set; }
        public Nullable<double> Defect_Qty { get; set; }
        public string Customer { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
    }
}
