//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SQE_Vendor_Score_Ref
    {
        public string Vendor { get; set; }
        public byte Category_ID { get; set; }
        public byte Index { get; set; }
        public Nullable<double> Value_From { get; set; }
        public Nullable<double> Value_To { get; set; }
        public Nullable<int> Score { get; set; }
        public string Result { get; set; }
        public string Other { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
    }
}
