//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Inv_Subject_Matter_List
    {
        public string Subject_Matter_ID { get; set; }
        public string Subject_Matter_Name { get; set; }
        public string Feild { get; set; }
        public string Area { get; set; }
    }
}
