//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SQE_PCN
    {
        public string PCN_Num { get; set; }
        public string Supplier_Name { get; set; }
        public string Other_Name { get; set; }
        public string Supplier_Add { get; set; }
        public Nullable<System.DateTime> Req_Date { get; set; }
        public string MI_Part { get; set; }
        public string MI_Attached { get; set; }
        public string Afftect_Desc { get; set; }
        public string PCN_Class { get; set; }
        public string Other_Class { get; set; }
        public Nullable<System.DateTime> Imp_Plan { get; set; }
        public string Chg_Desc { get; set; }
        public string Chg_Reason { get; set; }
        public string Chg_Effect { get; set; }
        public string Test_Result { get; set; }
        public string Remark { get; set; }
        public string Supplier_Signature { get; set; }
        public Nullable<System.DateTime> Supplier_Date_Sign { get; set; }
        public string PCN_Status { get; set; }
        public string Dec_Reason { get; set; }
        public string QRB_Sign { get; set; }
        public Nullable<System.DateTime> QRB_Date { get; set; }
        public string Procurement { get; set; }
        public Nullable<System.DateTime> Procurement_Date { get; set; }
        public string Supplier_QA { get; set; }
        public Nullable<System.DateTime> QA_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
    }
}
