//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SQE_Develop_ImprovePlan
    {
        public long ID { get; set; }
        public string Source_From { get; set; }
        public string Category { get; set; }
        public string Supplier_Code { get; set; }
        public string Part { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<byte> Risk_Level { get; set; }
        public Nullable<double> Quality { get; set; }
        public Nullable<double> Delivery { get; set; }
        public Nullable<double> Cust_Claim { get; set; }
        public Nullable<double> Freight { get; set; }
        public Nullable<int> Pro_Desc { get; set; }
        public Nullable<int> Goal { get; set; }
        public string Scar_Action { get; set; }
        public string Other_Action { get; set; }
        public string Owner { get; set; }
        public Nullable<System.DateTime> Due_date { get; set; }
        public string Status { get; set; }
        public string Comment { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
    }
}
