//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Inv_Email_Remind
    {
        public string Sug_ID { get; set; }
        public string Step_ID { get; set; }
        public string Step_Owner { get; set; }
        public string Mail_To { get; set; }
        public string Mail_CC { get; set; }
        public string Mail_Subject { get; set; }
        public string Mail_Content { get; set; }
        public Nullable<byte> Send_Time { get; set; }
        public Nullable<bool> Has_Action { get; set; }
    }
}
