//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SQE_SupplierLog_Contact
    {
        public long ID { get; set; }
        public string Supplier_Code { get; set; }
        public string Contact_Name { get; set; }
        public string Contact_Tilte { get; set; }
        public string Contact_Email { get; set; }
        public string Contact_Phone { get; set; }
    }
}
