//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SQE_SupplierLog_QMS
    {
        public int ID { get; set; }
        public string Supplier_Code { get; set; }
        public string QMS { get; set; }
        public System.DateTime Certification_Date { get; set; }
        public System.DateTime DueDate { get; set; }
    }
}
