//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLaborScan
    {
        public long ID { get; set; }
        public string OperID { get; set; }
        public string OperName { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public string Action { get; set; }
        public string WC { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> RealTimeWorking { get; set; }
        public Nullable<decimal> TotalTime { get; set; }
    }
}
