//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBTOOL
    {
        public string FIX_ID { get; set; }
        public string FIX_NAME { get; set; }
        public string FIX_DESC { get; set; }
        public string EVA_METHOD { get; set; }
        public string STATUS { get; set; }
        public string LINE { get; set; }
        public string YN { get; set; }
        public string KIND { get; set; }
        public string DATE { get; set; }
        public string FREQUENCY { get; set; }
        public string FIX_TYPE { get; set; }
        public string YN_2 { get; set; }
        public string FREQUENCY_2 { get; set; }
        public string DATE_2 { get; set; }
        public string LOCATION { get; set; }
    }
}
