//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPLATE_DET
    {
        public int TEMPLATE_NUM { get; set; }
        public string TEMPLATE { get; set; }
        public int MEASURE_PARA { get; set; }
        public string MEASURE_PARA_DESC { get; set; }
        public string EVA_METHOD { get; set; }
    }
}
