//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDOR_Temp
    {
        public string CCN { get; set; }
        public string VENDOR { get; set; }
        public string PUR_LOC { get; set; }
        public string VEN_NAM { get; set; }
        public string ADDRESS { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string CTRY { get; set; }
        public string CONTACT { get; set; }
        public string EMAIL { get; set; }
        public string FAX { get; set; }
        public string TEL { get; set; }
    }
}
