//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vNCR_HDR
    {
        public int ID { get; set; }
        public string PO { get; set; }
        public string PN { get; set; }
        public string DESCR { get; set; }
        public string Supplier { get; set; }
        public string Supplier_code { get; set; }
        public string REV { get; set; }
        public Nullable<double> Qty { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> RPT_DATE { get; set; }
        public string Remark { get; set; }
        public string AQLM { get; set; }
        public string AQLV { get; set; }
        public string SPL1 { get; set; }
        public string SPL2 { get; set; }
        public string NCR { get; set; }
        public string IQA_Status { get; set; }
        public string CA { get; set; }
        public Nullable<System.DateTime> NCR_writen_Date { get; set; }
    }
}
