//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vNCR_DET
    {
        public Nullable<int> ID { get; set; }
        public int PartialID { get; set; }
        public string Non_Conformances { get; set; }
        public Nullable<double> NC_Qty { get; set; }
        public string Defect { get; set; }
        public string Response { get; set; }
        public string Disposition { get; set; }
        public string Remark { get; set; }
    }
}
