//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace II_VI_Incorporated_SCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VNMaterialTraceability
    {
        public string Id { get; set; }
        public string NCRNUM { get; set; }
        public string VNMaterialTraceability1 { get; set; }
        public Nullable<bool> IsPrint { get; set; }
    }
}
